import type { App } from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAdjust,
  faArrowDownLong,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowRotateLeft,
  faArrowsRotate,
  faArrowUp,
  faArrowUpLong,
  faBan,
  faBolt,
  faCartShopping,
  faCheck,
  faClockRotateLeft,
  faCommentSms,
  faDesktop,
  faDice,
  faDog,
  faDollarSign,
  faDungeon,
  faEdit,
  faEnvelope,
  faFloppyDisk,
  faHandFist,
  faHatWizard,
  faHome,
  faKey,
  faMagnifyingGlass,
  faMap,
  faMars,
  faMobile,
  faMoon,
  faNetworkWired,
  faPlus,
  faQuestion,
  faRobot,
  faSackDollar,
  faSun,
  faTablet,
  faUser,
  faVenus,
  faWeightHanging,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAdjust,
  faArrowDownLong,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowRotateLeft,
  faArrowsRotate,
  faArrowUp,
  faArrowUpLong,
  faBan,
  faBolt,
  faCartShopping,
  faCheck,
  faClockRotateLeft,
  faCommentSms,
  faDesktop,
  faDice,
  faDog,
  faDollarSign,
  faDungeon,
  faEdit,
  faEnvelope,
  faFloppyDisk,
  faHandFist,
  faHatWizard,
  faHome,
  faKey,
  faMagnifyingGlass,
  faMap,
  faMars,
  faMobile,
  faMoon,
  faNetworkWired,
  faPlus,
  faQuestion,
  faRobot,
  faSackDollar,
  faSun,
  faTablet,
  faUser,
  faVenus,
  faWeightHanging,
  faXmark,
);

export default function (app: App) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
